global using System;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using IslamicPOS.Core.Models;
global using IslamicPOS.Core.Models.Auth;
global using IslamicPOS.Core.Models.Reports;
global using IslamicPOS.Core.Models.IslamicFinance;
global using IslamicPOS.Core.Models.Logistics;
global using IslamicPOS.Core.Models.Inventory;