name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Publish Web
      run: dotnet publish src/IslamicPOS.Web/IslamicPOS.Web.csproj -c Release -o web-publish
    
    - name: Publish API
      run: dotnet publish src/IslamicPOS.Server/IslamicPOS.Server.csproj -c Release -o api-publish
    
    - name: Deploy Web to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: islamic-pos-web
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './web-publish'
    
    - name: Deploy API to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: islamic-pos-api
        publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
        package: './api-publish'