name: Configure Environment Secrets

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  configure-secrets:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Configure Azure Key Vault
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get Secrets from Key Vault
      uses: azure/get-keyvault-secrets@v1
      with:
        keyvault: 'islamic-pos-${{ github.event.inputs.environment }}'
        secrets: |
          DbConnection
          DbPassword
          PrinterConfig
          IslamicFinanceConfig
          StorageConnection
          ApiKey
      id: get-secrets

    - name: Set GitHub Secrets
      uses: azure/github-actions/set-secret@v1
      with:
        secret-name: 'DB_CONNECTION_${{ github.event.inputs.environment }}'
        secret-value: ${{ steps.get-secrets.outputs.DbConnection }}
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}