name: Staged Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.404'

    - name: Verify .NET installation
      run: dotnet --info

    - name: Clean
      run: dotnet clean ./IslamicPOS.sln --configuration Release

    - name: Restore dependencies
      run: dotnet restore ./IslamicPOS.sln

    - name: Build
      run: dotnet build ./IslamicPOS.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./IslamicPOS.sln --configuration Release --no-build