name: Staged Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Clear global.json
      run: rm -f global.json || true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.404'

    - name: Create global.json
      run: |
        echo '{
          "sdk": {
            "version": "8.0.404"
          }
        }' > global.json

    - name: Verify .NET version
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src

    - name: Test
      run: dotnet test --no-build
      working-directory: ./src