name: Build Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear
    
    - name: Restore dependencies
      run: dotnet restore --force
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
